const Icons = {
    account: '/icon-account.svg',
    download: '/icon-dl.svg',
    cart: '/icon-cart.svg',
    defilement: '/icon-defilement.svg',
    expand: '/icon-expand.svg',
    languages: '/icon-languages.svg',
    rightArrow: '/icon-right-arrow.svg',
    search: '/search.svg',
    logo: '/logo.svg',
    showPw: '/show-pw.svg',
    check: '/check.svg',
    circleCheck: '/circle-check.svg',
    circleNotCheck: '/circle-not-check.svg',
    glyphCoin: '/img/glyph-coin.png',
    binaryCoin: '/img/binary-coin.png',
    edit: '/edit-icon.svg',
    paypal: '/img/paypal.png',
    mastercard: '/img/mastercard.png',
    credit: '/img/credit.png',
    bucket: '/bucket.svg',
    backArrow: '/back-arrow.svg',
    connectAccount: '/connect-account.svg',
    warning: '/warning-icon.svg',
    success: '/success.svg',
    glyphGb: '/glyph-bg.svg',
    lock: '/lock.svg',
    burger: '/burger.svg',
};

export { Icons };
